version: '3'

services:
  neo4j:
    image: neo4j:4.4.40
    network_mode: "bridge"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,algo.*
      - NEO4J_dbms_security_procedures_whitelist=apoc.*,algo.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_shell_enabled=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science", "n10s"]
#    volumes:
#      - ./volume/plugins:/plugins
#      - ./volume/data:/data
#      - ./volume/import:/import
#docker run -it --rm --publish=7474:7474 --publish=7687:7687 --env NEO4J_AUTH=none --env NEO4J_PLUGINS='["graph-data-science"]' --env NEO4JLABS_PLUGINS='["apoc", "n10s"]' neo4j:5.26.0-ubi9
