version: '3.3'

networks:
  cstone157:
    driver: bridge

volumes:
    grafana_data: {}

services:
  loki:
    container_name: loki
    image: grafana/loki:2.3.0
    restart: unless-stopped
    ports:
      - "3100:3100"
    volumes:
      - ./loki/config/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./loki/data:/data/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      - cstone157
    labels:
      org.label-schema.group: "cstone157"
