version: '3.3'

networks:
  cstone157:
    driver: bridge

volumes:
    grafana_data: {}

services:
  caddy:
    image: caddy:2.3.0
    container_name: caddy
    ports:
      - "3000:3000"  # Grafana's Port
      - "9090:9090"  # Prometheus's Port
      - "9093:9093"  # Alertmanager's Port
      - "9091:9091"  # Pushgateway's Port
    volumes:
      - ./caddy:/etc/caddy
    environment:
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-JDJhJDE0JE91S1FrN0Z0VEsyWmhrQVpON1VzdHVLSDkyWHdsN0xNbEZYdnNIZm1pb2d1blg4Y09mL0ZP}
    restart: unless-stopped
    networks:
      - cstone157
    labels:
      org.label-schema.group: "cstone157"