apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  
  # V1
  #drink: {{ .Values.favoriteDrink }}

  drink: {{ .Values.favorite.drink }}
  food: {{ .Values.favorite.food }}

