apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest  # Use the official pgAdmin image
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "admin@example.com"  # Replace with your desired email
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "password"  # Replace with a strong password!  Important for security.
        # Add liveness and readiness probes for better health management
        livenessProbe:
          httpGet:
            path: /login
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /login
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin  # Mount a persistent volume for data
      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-pvc  # Reference the PVC (PersistentVolumeClaim)
