apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode as needed (e.g., ReadWriteMany if supported by your storage)
  resources:
    requests:
      storage: 10Gi  # Adjust the storage size as needed
  #storageClassName: standard # Or another storage class if you have one configured 