apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
spec:
  type: NodePort  # or NodePort or LoadBalancer, depending on your needs
  selector:
    app: pgadmin
  ports:
  - protocol: TCP
    port: 80
    #targetPort: 80
    nodePort: 30000
    name: http