services:
  # Standard RStudio deployment, default user name is rstudio
  rstudio:
    image: rocker/rstudio:4.2.2
    ports:
    - 8888:8787
    environment:
      - USERNAME=rstudio
      - PASSWORD=password
    volumes:
    - ./work:/home/rstudio
    container_name: rstudio
