apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Or ReadWriteMany if supported by your storage
  resources:
    requests:
      storage: 10Gi   # Adjust storage size as needed