version: '3.3'

networks:
  cstone157:
    driver: bridge

volumes:
    grafana_data: {}

services:
  grafana:
    image: grafana/grafana:9.0.3
    container_name: grafana
    user: "0"
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: unless-stopped
    links:
      - postgres
    expose:
      - 3000
    networks:
      - cstone157
    labels:
      org.label-schema.group: "cstone157"
