version: '3.3'

networks:
  cstone157:
    driver: bridge

volumes:
    grafana_data: {}

services:
  pushgateway:
    image: prom/pushgateway:v1.4.3
    container_name: pushgateway
    restart: unless-stopped
    expose:
      - 9091
    networks:
      - cstone157
    labels:
      org.label-schema.group: "cstone157"