version: "3"
services:
  # Custom datascience-notebook, for us to use
  jupyter_datacamp2:
    build: .
    image: cstone158/jupyter_datacamp2
    volumes:
    - ./work:/home/jovyan/work
    ports:
    - 8000:8888
    container_name: jupyter_datacamp2
