# Use the jupyter datascience-notebook
FROM jupyter/datascience-notebook

RUN pip install plotly
#RUN pip install nltk
#RUN pip install pytest ipytest
#RUN pip install nxviz
#RUN jupyter labextension install jupyterlab-plotly
#RUN pip install mlflow
#RUN pip install bokeh====2.4.3
#RUN pip install jupyter_bokeh
#RUN jupyter labextension install @bokeh/jupyter_bokeh